/*
 * ===========================================
 * Java Pdf Extraction Decoding Access Library
 * ===========================================
 *
 * Project Info:  http://www.idrsolutions.com
 * Help section for developers at http://www.idrsolutions.com/java-pdf-library-support/
 *
 * (C) Copyright 1997-2013, IDRsolutions and Contributors.
 *
 * 	This file is part of JPedal
 *
     This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


 *
 * ---------------
 * General.java
 * ---------------
 */

package org.jpedal.objects.acroforms.gui.certificates;

public class General extends javax.swing.JPanel {

	private static final long serialVersionUID = -7645736093977724532L;

	/**
	 * Creates new form General
	 */
	public General() {
		initComponents();
	}

	public void setValues(String name, String notBefore, String notAfter) {
		// TODO Auto-generated method stub
		this.issuedToBox.setText(name);
		this.validFromBox.setText(notBefore);
		this.validToBox.setText(notAfter);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
	private void initComponents() {

		this.jLabel1 = new javax.swing.JLabel();
		this.validToBox = new javax.swing.JLabel();
		this.jLabel3 = new javax.swing.JLabel();
		this.jLabel4 = new javax.swing.JLabel();
		this.issuedToBox = new javax.swing.JLabel();
		this.validFromBox = new javax.swing.JLabel();

		setLayout(null);

		this.jLabel1.setText("Valid to:");
		add(this.jLabel1);
		this.jLabel1.setBounds(10, 70, 80, 20);
		add(this.validToBox);
		this.validToBox.setBounds(80, 70, 310, 20);

		this.jLabel3.setText("Valid from:");
		add(this.jLabel3);
		this.jLabel3.setBounds(10, 40, 80, 20);

		this.jLabel4.setText("Issued to:");
		add(this.jLabel4);
		this.jLabel4.setBounds(10, 10, 80, 20);
		add(this.issuedToBox);
		this.issuedToBox.setBounds(80, 10, 310, 20);
		add(this.validFromBox);
		this.validFromBox.setBounds(80, 40, 310, 20);
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel issuedToBox;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel validFromBox;
	private javax.swing.JLabel validToBox;
	// End of variables declaration//GEN-END:variables
}
